### ISSUE TITLE
建议增加角膜病和结膜病，程序员都容易用眼过度

### ISSUE THREAD

**Issue by lanletter** [gnoloehz/996.OD#10]
建议增加角膜病和结膜病，程序员都容易用眼过度

**Comment by MagicWiner** [comment]
Code的多年，眼科就是我常去的，都感觉要办理个“VIP”了

**Comment by gnoloehz** [comment]
直接提pull request吧

**Comment by lanletter** [comment]
> @lanletter @MagicWiner 直接提pull request吧

大佬给我个权限吧

**Comment by MagicWiner** [comment]
> @lanletter @MagicWiner 直接提拉请求吧

给个权限

**Comment by gnoloehz** [comment]
@lanletter @MagicWiner fork以后提交到自己的repo，然后提pull request，谢谢
