### ISSUE TITLE
建议加入梨状肌综合征

### ISSUE THREAD

**Issue by pengzee** [gnoloehz/996.OD#16]
梨状肌综合征是引起急慢性坐骨神经痛的常见疾病。一般认为，腓总神经高位分支，自梨状肌肌束间穿出或坐骨神经从梨状肌肌腹中穿出。当梨状肌受到损伤，发生充血、水肿、痉挛、粘连和挛缩时，该肌间隙或该肌上，下孔变狭窄，挤压其间穿出的神经、血管，因此而出现的一系列临床症状和体症称为梨状肌损伤综合征。

非手术方法包括推拿手法治疗、局部封闭、肌注、理疗、中草药、针灸等。推拿手法治疗是治疗梨状肌综合征的主要方法，可以明显改善症状，缓解患者的痛苦。采用手法治疗时，首先要选准部位。患者可取俯卧位，双下肢后伸，使腰臀部肌肉放松。术者自髂后上棘到股骨大粗隆做一连线，连线中点直下2cm处即为坐骨神经出梨状肌下孔之部位，其两侧即为梨状肌。局部封闭对缓解疼痛有一定作用。

**Comment by gnoloehz** [comment]
请提交pr，谢谢
