### ISSUE TITLE
腰椎间盘突出

### ISSUE THREAD

**Issue by ljw8947** [gnoloehz/996.OD#17]
1.治疗方法中建议删除“正骨 推拿”，这两个容易加深病情。一般来说治疗方案分为保守治疗和手术治疗，保守治疗 3个月没有效果，需要考虑手术。建议增加核磁共振检测，X光、CT看不出腰椎间盘突出。

2.腰椎间盘突出严重会导致压迫马尾神经，导致大小便失禁，并且影响性功能。

3.建议增加锻炼方式列。

**Comment by gnoloehz** [comment]
请直接提交pr
