### ISSUE TITLE
同抑郁症吃药中

### ISSUE THREAD

**Issue by warmilk** [gnoloehz/996.OD#19]
我是2018年的应届毕业生，在大三被当畜生用做实习生压榨了一年之后，大四结束准备毕业时候确诊的焦虑抑郁症，现在还在吃盐酸帕罗西汀治疗中，换了间不忙的公司，好多了。。。

**Comment by gnoloehz** [comment]
请提PR，将病情细分放到列表里

**Comment by gnoloehz** [comment]
请提PR，将病情细分放到列表里
