### ISSUE TITLE
建议再增加一个关于程序员怎么养生保健预防脱发的社区！

### ISSUE THREAD

**Issue by JacksonJack123456** [gnoloehz/996.OD#3]
建议再增加一个关于程序员怎么养生保健预防脱发的社区！

**Comment by frankxieke** [comment]
感觉可以啊，想法很赞

**Comment by frankxieke** [comment]
脱发是不是也算一种职业病

**Comment by zheolong** [comment]
@JacksonJack123456 脱发是个世界性难题，如果你没有家族遗传，并且生活其他方面健康，可以先添加下脱发的专业职业病描述到我们的表格里。

**Comment by jaune162** [comment]
跑偏了

**Comment by HiAscend** [comment]
哈哈，这样说，可以增加一个其他职业的。996不光是程序员

**Comment by dream80** [comment]
> @JacksonJack123456 脱发是个世界性难题，如果你没有家族遗传，并且生活其他方面健康，可以先添加下脱发的专业职业病描述到我们的表格里。

这个问题只有一个解决方法：理发😄！

**Comment by lazyhero** [comment]
……这个要看家族有没有秃头了……
