### ISSUE TITLE
是否可以将此宣传渠道加入首页

### ISSUE THREAD

**Issue by githubmll** [gnoloehz/996.OD#7]
![wx](https://user-images.githubusercontent.com/17825339/56355777-befd2680-6209-11e9-8af6-2491dc56300e.png)

**Comment by gnoloehz** [comment]
@githubmll 这个渠道是什么

**Comment by reinit** [comment]
> @githubmll 这个渠道是什么

FYI：https://github.com/996icu/996.ICU/pull/25450

**Comment by reinit** [comment]
> @githubmll 这个渠道是什么

FYI：https://github.com/996icu/996.ICU/pull/25450

**Comment by gnoloehz** [comment]
@githubmll 我觉得这个还是暂缓，谢谢
